### ISSUE TITLE
Implement editor

### ISSUE THREAD

**Issue by NickMuellner** [DrStrangeloovee/Elevate360#31] opened 2024-04-22 06:23 UTC
Implementing an editor which can be used at different pages, so it should be modular and independent. The editor can be used for example for taking notes. The editor should come with several inline markup features and is resizeable. A wireframe design is already done in the previous GItHub Issue.

**Comment by DrStrangeloovee** [comment] 2024-05-14 20:21
Duplicate of #39

**Closed by DrStrangeloovee** 2024-05-14 20:21 UTC
Labels: points:  2
